sudo: required
language: r
cache:
  - $HOME/.ccache
  - packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
jobs:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    env:
      - R_FUTURE_PLAN=multisession
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@development", dependencies = FALSE)'
    r_binary_packages:
      - BH
      - ellipsis
      - rlang
  - os: linux
    dist: xenial
    r: release
    env:
      - R_FUTURE_PLAN=multisession
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@development", dependencies = FALSE)'
    after_failure:
      - cat ./SpaDES.core.Rcheck/tests/test-all.Rout
    after_success:
      - travis_wait 15 Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
    r_binary_packages:
      - BH
      - dplyr
      - git2r
      - igraph
      - later
      - RCurl
      - rlang
      - stringi
      - XML
    r_github_packages:
      - jimhester/lintr
      - r-lib/covr
  - os: linux
    dist: xenial
    r: devel
    env:
      - R_FUTURE_PLAN=multisession
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - ccache
          - libgdal-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
      - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
    before_script:
      - Rscript -e 'install.packages(c("devtools", "qs"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@development", dependencies = FALSE)'
    r_binary_packages:
      - BH
      - dplyr
      - igraph
      - rlang
      - stringi
  - os: osx
    osx_image: xcode9.4
    env:
      - GLPK=true
      - R_FUTURE_PLAN=multisession
    addons:
      homebrew:
        packages:
        - glpk
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
      - Rscript -e 'install.packages(c("digest", "igraph", "qs", "rgdal", "rgeos"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@development", dependencies = FALSE)'
  - os: osx
    osx_image: xcode9.4
    env:
      - GLPK=false
      - R_FUTURE_PLAN=multisession
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
      - Rscript -e 'install.packages(c("digest", "igraph", "qs", "rgdal", "rgeos"), type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/reproducible@development", dependencies = FALSE)'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
