on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

name: test-coverage

jobs:
  test-coverage:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@master

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            fastshp=?ignore
            NLMR=?ignore
            PredictiveEcology/Require@development
            PredictiveEcology/reproducible@development
            PredictiveEcology/quickPlot@development
            PredictiveEcology/SpaDES.tools@development

      - name: Install additional package dependencies
        run: |
          pak::pkg_install("achubaty/NLMR")
          pak::pkg_install("s-u/fastshp")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
